In [18]:
import pandas as pd
import torch
import numpy as np

In [19]:
# define the apartment's rent

rent = 2550

# convert to an integer tensor

rent_tensor = torch.tensor(
    rent,
    dtype=torch.int)


In [20]:
print(rent_tensor)

tensor(2550, dtype=torch.int32)


In [21]:
print(rent_tensor.dtype)

torch.int32


In [22]:
# create a numpy array with the rent in US dollars,
# size in square feet, and age in years

apt_array = np.array([2550, 750, 3.5])

# convert to a tensor of floats

apt_tensor = torch.tensor(
    apt_array,
    dtype=torch.float)


In [23]:
print(apt_tensor)

tensor([2550.0000,  750.0000,    3.5000])


In [24]:
print(apt_tensor.dtype)

torch.float32


In [31]:
# convert a DataFrame named df to a PyTorch tensor

import pandas as pd

# Example: create a sample DataFrame 'df'

df = pd.DataFrame({
    'col1': [1, 2, 3],
    'col2': [4, 5, 6],
    'col3': [7, 8, 9]
})

tensor_pandas = torch.tensor(
    df.values,
    dtype=torch.float)

print(tensor_pandas)

tensor([[1., 4., 7.],
        [2., 5., 8.],
        [3., 6., 9.]])


In [29]:
print(df)

   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9


In [30]:
print(tensor_pandas)

tensor([[1., 4., 7.],
        [2., 5., 8.],
        [3., 6., 9.]])


In [32]:
print(tensor_pandas.dtype)

torch.float32


In [ ]:
# convert a DataFrame named df to a PyTorch tensor

import pandas as pd

# Example: create a sample DataFrame 'df'

df = pd.DataFrame({
    'col1': [1, 2, 3],
    'col2': [4, 5, 6],
    'col3': [7, 8, 9]
})

tensor_pandas = torch.tensor(
    df.values,
    dtype=torch.float)

#print(tensor_pandas)

tensor([[1., 4., 7.],
        [2., 5., 8.],
        [3., 6., 9.]])


In [ ]:
# convert a DataFrame named df to a PyTorch tensor

import pandas as pd

# Example: create a sample DataFrame 'df'

df = pd.DataFrame({
    'col1': [1, 2, 3],
    'col2': [4, 5, 6],
    'col3': [7, 8, 9]
})

tensor_pandas = torch.tensor(
    df.values,
    dtype=torch.float)

#print(tensor_pandas)

tensor([[1., 4., 7.],
        [2., 5., 8.],
        [3., 6., 9.]])
